@startuml

skinparam ranksep 120

'게임 오브젝트
abstract class GameObject {
    int hp
}

' 테란 계층구조
abstract class Terran extends GameObject

abstract class TerranUnit extends Terran implements Moveable

abstract class TerranStructure extends Terran

' 테란 유닛
class Marine extends TerranUnit implements Attackable, Bionic, Behealed

class Medic extends TerranUnit implements Healable, Bionic, Behealed

class Tank extends TerranUnit implements Attackable, Mechanic

class Vulture extends TerranUnit implements Attackable, Mechanic

class Scv extends TerranUnit implements Harvestable, Repairable, Mechanic, Behealed

' 인터페이스
interface Healable {
    void heal(Behealed behealed)
}

interface Repairable {
    void repair(Mechanic mechanic)
}

interface Harvestable {
    Gas harvestGas()
    Minerals harvestMinerals()
}

interface Attackable implements Groupable {
    void attack()
}

interface Behealed { }

interface Bionic { }

interface Mechanic { }

interface Moveable implements Groupable {
    void move()
}

interface Groupable { }

interface Productable {
    TerranUnit produce(Minerals minerals Gas gas)
}

GameObject -[hidden]-> Terran
GameObject -[hidden]-> Groupable
Terran -[hidden]-> TerranUnit
Terran -[hidden]-> TerranStructure
Scv -[hidden]-> Productable

@enduml