@startuml

scale 1.5

class Hero {
    String name;
    int _age;

    void attack(Slime slime)
}

class SuperHero extends Hero {
}

class Wizard {
    String name;
    int hp;
    int mp;

    void heal(Hero hero)
}

class GreatWizard extends Wizard {

    void superHeal(Hero hero)
}

@enduml