@startuml

skinparam ranksep 120

'게임 오브젝트
abstract class GameObject {
    int hp
}

' 종족
together {
abstract class Zerg extends GameObject implements SelfHealable, Bionic

abstract class Terran extends GameObject

abstract class Protoss extends GameObject implements Barrier
}


' 건물, 유닛
together {
abstract class TerranUnit extends Terran implements Moveable

abstract class TerranStructure extends Terran

abstract class ZergUnit extends Zerg implements Moveable

abstract class ZergStructure extends Zerg implements Bionic

abstract class ProtossUnit extends Protoss implements Moveable

abstract class ProtossStructure extends Protoss
}


' 테란 유닛
class Marine extends TerranUnit implements Attackable, Bionic, Behealed

class Medic extends TerranUnit implements Healable, Bionic, Behealed

class Tank extends TerranUnit implements Attackable, Mechanic

class Vulture extends TerranUnit implements Attackable, Mechanic

class Scv extends TerranUnit implements Harvestable, Repairable, Mechanic, Behealed

' 저그 유닛
class Zergling extends ZergUnit implements Behealed, Attackable

class Hydra extends ZergUnit implements Behealed, Attackable

' 토스 유닛
class Zealot extends ProtossUnit implements Behealed, Bionic, Attackable

class Dragun extends ProtossUnit implements Mechanic, Attackable

' 자원
class Gas extends GameObject

class Mineral extends GameObject

' 인터페이스
interface SelfHealable {
    void selfHeal()
}

interface Healable {
    void heal(Behealed behealed)
}

interface Repairable {
    void repair(Mechanic mechanic)
}

interface Harvestable {
    Gas harvestGas()
    Minerals harvestMinerals()
}

interface Attackable implements Groupable {
    void attack()
}

interface Productable {
    TerranUnit produce(Minerals minerals, Gas gas)
}

interface Behealed { }

interface BeRefaired { }

interface Barrier implements SelfHealable {
    int barrier
 }

interface Bionic { }

interface Mechanic implements BeRefaired { }

interface Moveable implements Groupable {
    void move()
 }

interface Groupable { }

GameObject -[hidden]-> Zerg
GameObject -[hidden]-> Terran
GameObject -[hidden]-> Protoss
Zerg -[hidden]-> ZergUnit
Terran -[hidden]-> TerranUnit
Protoss -[hidden]-> ProtossUnit
Zerg -[hidden]-> ZergStructure
Terran -[hidden]-> TerranStructure
Protoss -[hidden]-> ProtossStructure
Scv -[hidden]-> Productable

@enduml